name: meilisearch-docsearch-scraper

on:
  push:
    branches:
      - master
    paths:
      - 'docs/src/content/**'

  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}

jobs:
  scrape:
    name: Scrape documentation and update Meilisearch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Meilisearch Docs Scraper
        run: |
          docker run -t --rm --network=host \
            -e MEILISEARCH_HOST_URL='${{ secrets.MEILISEARCH_HOST_URL }}' \
            -e MEILISEARCH_API_KEY='${{ secrets.MEILISEARCH_API_KEY }}' \
            -v ${{ github.workspace }}/docs/docsearch.config.json:/docs-scraper/config.json \
            getmeili/docs-scraper:latest pipenv run ./docs_scraper config.json
